name: 清除workflow

on:
  watch:
    types: [started]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:


env:
  TZ: Asia/Shanghai

jobs:
  delete:
    runs-on: ubuntu-latest
      
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 1
