name: xml2json

on:
  push:
    branches: [ "main" ]
  #schedule:
    #- cron: 0 4,10,16,22 * * *
    #- cron: 36 15,16 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - url: https://epg.112114.xyz/pp.xml.gz
            branch: main
          #- url: http://epg.51zmt.top:8000/e.xml
            #branch: master

    steps:
      - name: download files
        run: |
          #wget https://raw.bgithub.xyz/${{ github.repository }}/${{ matrix.branch }}/md5.txt -O md5.txt
          url="${{ matrix.url }}"
          if [[ "$url" == *".gz" ]]; then
            echo "url is end with gz"
            wget $url -O e.xml.gz
            gzip -df e.xml.gz
          else
            echo "url is not end with gz"
            wget $url -O e.xml
          fi

      - name: check md5
        run: |
          pwd
          ls
          md5=$(md5sum ./e.xml | awk '{print $1}')
          if ! grep -q "$md5" ./md5.txt; then
            echo "isDiff=$md5" >> $GITHUB_ENV
          fi

      - name: checkout code
        uses: actions/checkout@v4
        if: ${{ env.isDiff }}
        with:
          ref: ${{ matrix.branch }}
          path: epg
        #with:
            #sparse-checkout: |
                #epg
                
      - name: xml to json
        if: ${{ env.isDiff }}
        working-directory: epg
        run: |
          cd "../"
          echo "到上级目录"
          pwd
          ls
          cd "epg"
          echo "到epg"
          ls
          #mv -f ../e.xml ./e.xml
          pwd ls
          #pip3 install -r requirements.txt
          #python3 xml2json.py
          
